#----------Auth-----------
@baseUrl = http://localhost:8085/api

###login
POST {{baseUrl}}/auth
Content-Type: application/json

{
    "username": "kotsu",
    "password": "Pepe1234$$"
}

###register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "username": "kotsu",
    "phone": 52345678,
    "email": "kotsuleemotsume@gmail.com",
    "role": "ADMIN",
    "password": "Pepe1234$$"
}

###confirm account
POST {{baseUrl}}/confirmAccount
Content-Type: application/json

{
    "username": "kotsu",
    "code": "DEpFDL"
}

